In [1]:
import numpy as np

In [2]:
random_arr = np.random.randint(1, 20, size=(2, 3, 4, 5))
display(random_arr)
# 2 parent array with 3 sub-array that contains 4 rows with 5 elements
'''
2 parent arrays (outermost dimension)
Each parent array contains 3 sub-arrays (next dimension)
Each sub-array has 4 rows
Each row contains 5 elements
- from ChatGPT
'''

array([[[[ 3, 15, 18,  6,  7],
         [ 2, 15,  2,  7,  5],
         [ 2, 14,  9,  9, 15],
         [17, 10, 17,  5,  2]],

        [[ 6, 11,  9, 18,  5],
         [ 6,  4, 11, 19,  5],
         [ 7,  2, 12, 14,  3],
         [ 2, 18,  5,  9,  8]],

        [[18, 15,  2,  2,  3],
         [13, 12,  4,  6,  8],
         [ 9, 17, 14, 17,  7],
         [ 5, 19,  9, 12,  8]]],


       [[[14,  4, 10,  3, 14],
         [ 4, 16,  6,  8, 10],
         [16, 14, 19, 11, 11],
         [ 7, 12,  2, 16, 10]],

        [[11,  3, 13,  5, 13],
         [11, 18, 12, 17, 18],
         [14,  7,  6,  3, 19],
         [ 5, 15, 12,  8,  8]],

        [[ 8,  5,  1, 18, 15],
         [ 3,  9, 14, 17, 11],
         [17,  4,  8, 18, 12],
         [18,  9,  4,  6, 18]]]])

'\n2 parent arrays (outermost dimension)\nEach parent array contains 3 sub-arrays (next dimension)\nEach sub-array has 4 rows\nEach row contains 5 elements\n- from ChatGPT\n'

In [3]:
display(random_arr)

array([[[[ 3, 15, 18,  6,  7],
         [ 2, 15,  2,  7,  5],
         [ 2, 14,  9,  9, 15],
         [17, 10, 17,  5,  2]],

        [[ 6, 11,  9, 18,  5],
         [ 6,  4, 11, 19,  5],
         [ 7,  2, 12, 14,  3],
         [ 2, 18,  5,  9,  8]],

        [[18, 15,  2,  2,  3],
         [13, 12,  4,  6,  8],
         [ 9, 17, 14, 17,  7],
         [ 5, 19,  9, 12,  8]]],


       [[[14,  4, 10,  3, 14],
         [ 4, 16,  6,  8, 10],
         [16, 14, 19, 11, 11],
         [ 7, 12,  2, 16, 10]],

        [[11,  3, 13,  5, 13],
         [11, 18, 12, 17, 18],
         [14,  7,  6,  3, 19],
         [ 5, 15, 12,  8,  8]],

        [[ 8,  5,  1, 18, 15],
         [ 3,  9, 14, 17, 11],
         [17,  4,  8, 18, 12],
         [18,  9,  4,  6, 18]]]])

In [4]:
display(random_arr[0])

array([[[ 3, 15, 18,  6,  7],
        [ 2, 15,  2,  7,  5],
        [ 2, 14,  9,  9, 15],
        [17, 10, 17,  5,  2]],

       [[ 6, 11,  9, 18,  5],
        [ 6,  4, 11, 19,  5],
        [ 7,  2, 12, 14,  3],
        [ 2, 18,  5,  9,  8]],

       [[18, 15,  2,  2,  3],
        [13, 12,  4,  6,  8],
        [ 9, 17, 14, 17,  7],
        [ 5, 19,  9, 12,  8]]])

In [5]:
display(random_arr[1])

array([[[14,  4, 10,  3, 14],
        [ 4, 16,  6,  8, 10],
        [16, 14, 19, 11, 11],
        [ 7, 12,  2, 16, 10]],

       [[11,  3, 13,  5, 13],
        [11, 18, 12, 17, 18],
        [14,  7,  6,  3, 19],
        [ 5, 15, 12,  8,  8]],

       [[ 8,  5,  1, 18, 15],
        [ 3,  9, 14, 17, 11],
        [17,  4,  8, 18, 12],
        [18,  9,  4,  6, 18]]])

In [6]:
display(random_arr[0][0])

array([[ 3, 15, 18,  6,  7],
       [ 2, 15,  2,  7,  5],
       [ 2, 14,  9,  9, 15],
       [17, 10, 17,  5,  2]])

In [7]:
display(random_arr[0][1])

array([[ 6, 11,  9, 18,  5],
       [ 6,  4, 11, 19,  5],
       [ 7,  2, 12, 14,  3],
       [ 2, 18,  5,  9,  8]])

In [8]:
display(random_arr[0][2])

array([[18, 15,  2,  2,  3],
       [13, 12,  4,  6,  8],
       [ 9, 17, 14, 17,  7],
       [ 5, 19,  9, 12,  8]])

### The number of indices determines which part of the array we want to access

In [9]:
display(random_arr[0][0][0][0])
# If we want to display a single element from the array, then it needs to match the length of shape which is 4

3

In [10]:
display(random_arr[0][0][0])

array([ 3, 15, 18,  6,  7])

In [11]:
display(random_arr[0][0])

array([[ 3, 15, 18,  6,  7],
       [ 2, 15,  2,  7,  5],
       [ 2, 14,  9,  9, 15],
       [17, 10, 17,  5,  2]])

In [12]:
display(random_arr[0])

array([[[ 3, 15, 18,  6,  7],
        [ 2, 15,  2,  7,  5],
        [ 2, 14,  9,  9, 15],
        [17, 10, 17,  5,  2]],

       [[ 6, 11,  9, 18,  5],
        [ 6,  4, 11, 19,  5],
        [ 7,  2, 12, 14,  3],
        [ 2, 18,  5,  9,  8]],

       [[18, 15,  2,  2,  3],
        [13, 12,  4,  6,  8],
        [ 9, 17, 14, 17,  7],
        [ 5, 19,  9, 12,  8]]])