In [1]:
import numpy as np

### What is NumPy?
NumPy stands for NumericalPython


NumPy is the foundation for converting your data into numbers

### Why NumPy?
- Fast
- Optimizations written in C
- Vectorization via broadcasting (avoiding loops)
- Backbone of other Python scientific packages

### Data Types & Attributes
NumPy's main data type is ndarray

In [2]:
a1 = np.array([1, 2, 3, 4, 5])
display(a1)
a1.shape
# Shape = (1, 5) 1 row with 5 columns
# Vector is a 1-D array

array([1, 2, 3, 4, 5])

(5,)

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2, 3], [4.5, 5.5, 6.5]])
display(a2)
a2.shape
# Shape = (2, 3) 2 row with 3 columns
# Matrix is a 2-D or more array


array([[1. , 2. , 3. ],
       [4.5, 5.5, 6.5]])

(2, 3)

In [5]:
a3 = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
               ])
display(a3)
a3.shape
# Shape = (2, 3, 3) 2 row with 3 columns and 3 columns
# Matrix is a 2-D or more array

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

(2, 3, 3)

### Get Number of Dimensions

In [6]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

### Get Data Type

In [7]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

### Get Size of the Array
How many elements does it contain?

In [8]:
a1.size, a2.size, a3.size

(5, 6, 18)

### Get Type

In [9]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

### Create a DataFrame from a NumPy array

In [10]:
import pandas as pd
df = pd.DataFrame(a2)
display(df)

0    1    2
0  1.0  2.0  3.0
1  4.5  5.5  6.5

### Creating Arrays

In [11]:
sample_arr = np.array([1, 2, 3, 4, 5])
sample_arr
# But what if the we don't want to manually input these elements?

array([1, 2, 3, 4, 5])

In [12]:
o1 = np.ones(2, dtype=int)
o1
# We can specify the shape and dtype of ones

array([1, 1])

In [13]:
o2 = np.ones((5, 3), dtype=int)
o2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [14]:
z1 = np.zeros((3,5), dtype=int)
z1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [15]:
range_arr = np.arange(1, 5)
range_arr
# Similar to how for in range loop works
# 1 is start and 5 is the end, so [1, 2, 3, 4]

array([1, 2, 3, 4])

In [16]:
r_arr = np.arange(0, 10, 2)
r_arr

array([0, 2, 4, 6, 8])

In [17]:
random_arr = np.random.randint(1, 100, size=(3, 5))
display(random_arr)
# 3 columns with 5 random elements per row
display(random_arr.shape)
display(random_arr.size)

array([[79, 44, 80,  5, 10],
       [71, 31, 10, 99, 45],
       [12, 57, 33,  7, 80]])

(3, 5)

15

In [18]:
random_arr2 = np.random.random((5, 3))
display(random_arr2)
# Generates a rabdom number greater than or equal to 0, but strictly less than 1.
# 5 columns with 3 random elements per row

array([[0.07418587, 0.94699945, 0.27709829],
       [0.99687706, 0.28096135, 0.18321764],
       [0.32849189, 0.50423707, 0.90947987],
       [0.22704308, 0.69988604, 0.30393024],
       [0.18296326, 0.50176047, 0.93393871]])

In [19]:
random_arr3 = np.random.rand(5, 3)
display(random_arr3)
display(random_arr3.shape)
display(random_arr3.size)
display(random_arr3.ndim)


array([[0.6502648 , 0.25240483, 0.42355228],
       [0.59246664, 0.20111199, 0.26538563],
       [0.64543217, 0.57060228, 0.4652976 ],
       [0.12953751, 0.75044726, 0.97417905],
       [0.34768319, 0.62855386, 0.40959845]])

(5, 3)

15

2

### Take Note of d0, d1, d2 - dimension

The key distinction is that np.random.rand() allows you to specify the dimensions of the output array, while np.random.random() always generates a single random float.

In summary, if you need a single random number, either function will work. However, if you need to generate a multidimensional array of random numbers, np.random.rand() is the appropriate choice.

### Number of Square Brackets represent the ARRAY - DIMENSION
### Setting the Shape attributes makes the ARRAY - 2D?


In [20]:
# Pseudo-random numbers
np.random.seed(8)

random_arr4 = np.random.rand(3, 3)
random_arr4

array([[0.8734294 , 0.96854066, 0.86919454],
       [0.53085569, 0.23272833, 0.0113988 ],
       [0.43046882, 0.40235136, 0.52267467]])

In [21]:
random_arr4
# These numbers are random, but the purpose of random.seed() is we want others to use our notebook and generate random numbers the same as ours?

array([[0.8734294 , 0.96854066, 0.86919454],
       [0.53085569, 0.23272833, 0.0113988 ],
       [0.43046882, 0.40235136, 0.52267467]])

### Get Unique Elements

In [26]:
random_arr5 = np.random.randint(1, 20, (3, 5))
display(random_arr5)
np.unique(random_arr5)

array([[10,  6, 15, 18, 12],
       [16, 12, 14,  9, 16],
       [11,  1,  8, 14,  3]])

array([ 1,  3,  6,  8,  9, 10, 11, 12, 14, 15, 16, 18])

### Viewing Arrays and Matrices

In [33]:
display(a1)
display(f'Last Element: {a1[-1]}')
display(f'First Element: {a1[0]}')

array([1, 2, 3, 4, 5])

'Last Element: 5'

'First Element: 1'

In [38]:
display(a2)
display(a2[0])
display(a2[1])

# Get 1st Element of the 1st sub-array
display(a2[0][0])

# Get last Element of the 1st sub-array
display(a2[0][-1])

# Get 1st Element of the 2nd sub-array
display(a2[1][0])

# Get last Element of the 2nd sub-array
display(a2[1][-1])

array([[1. , 2. , 3. ],
       [4.5, 5.5, 6.5]])

array([1., 2., 3.])

array([4.5, 5.5, 6.5])

1.0

3.0

4.5

6.5

In [51]:
display(a3)
display(a3[0][2])

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

array([7, 8, 9])

In [62]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4
# 5 elements, 4 rows, 3 columns, 2 parent array

array([[[[0, 7, 3, 1, 1],
         [1, 7, 7, 1, 9],
         [9, 6, 5, 0, 6],
         [8, 5, 2, 3, 4]],

        [[9, 7, 6, 7, 9],
         [2, 0, 5, 9, 3],
         [5, 4, 2, 7, 6],
         [5, 2, 5, 5, 9]],

        [[5, 0, 1, 6, 8],
         [8, 8, 6, 2, 7],
         [7, 1, 2, 6, 6],
         [6, 0, 9, 1, 5]]],


       [[[2, 6, 5, 8, 5],
         [7, 2, 6, 4, 7],
         [6, 8, 2, 6, 4],
         [5, 0, 3, 3, 5]],

        [[1, 6, 9, 1, 1],
         [5, 3, 2, 1, 7],
         [0, 5, 7, 7, 0],
         [9, 5, 4, 0, 3]],

        [[7, 6, 6, 6, 9],
         [0, 7, 9, 6, 0],
         [6, 7, 7, 0, 2],
         [3, 4, 7, 0, 9]]]])

In [56]:
a4.shape, a4.ndim

((2, 3, 4, 4), 4)

In [64]:
display(a4[1][1][0])

array([1, 6, 9, 1, 1])