# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()
one_dimension_arr = np.array([1, 2, 3, 4, 5])

# Create a 2-dimensional NumPy array using np.array()
two_dimension_arr = np.array([[1, 2, 3, 4, 5], 
                              [6, 7, 8, 9, 10]])

# Create a 3-dimensional Numpy array using np.array()
three_dimension_arr = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                                ])

display(one_dimension_arr)
display(two_dimension_arr)
display(three_dimension_arr)

array([1, 2, 3, 4, 5])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
display(one_dimension_arr.shape)
display(one_dimension_arr.ndim)
display(one_dimension_arr.dtype)
display(one_dimension_arr.size)
display(type(one_dimension_arr))

(5,)

1

dtype('int32')

5

numpy.ndarray

In [5]:
# Attributes of 2-dimensional array
display(two_dimension_arr.shape)
display(two_dimension_arr.ndim)
display(two_dimension_arr.dtype)
display(two_dimension_arr.size)
display(type(two_dimension_arr))


(2, 5)

2

dtype('int32')

10

numpy.ndarray

In [6]:
# Attributes of 3-dimensional array
display(three_dimension_arr.shape)
display(three_dimension_arr.ndim)
display(three_dimension_arr.dtype)
display(three_dimension_arr.size)
display(type(three_dimension_arr))

(2, 3, 3)

3

dtype('int32')

18

numpy.ndarray

In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame({'One Dimension Array' : one_dimension_arr})
df


One Dimension Array
0                    1
1                    2
2                    3
3                    4
4                    5

In [8]:
# Create an array of shape (10, 2) with only ones
arr_ones = np.ones(shape=(10, 2), dtype=int)
display(arr_ones)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [22]:
# Create an array of shape (7, 2, 3) of only zeros
arr_zeros = np.zeros(shape=(7, 2, 3), dtype=int)
display(arr_zeros)

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [10]:
# Create an array within a range of 0 and 100 with step 3
arr_range = np.arange(0, 100, 3)
display(arr_range)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [11]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_arr_int = np.random.randint(0, 10, size=(7, 2))
display(random_arr_int)


array([[8, 9],
       [4, 6],
       [0, 0],
       [7, 1],
       [4, 1],
       [9, 4],
       [3, 4]])

In [12]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_arr_float = np.random.random(size=(3, 5))
display(random_arr_float)

array([[0.5810517 , 0.30572179, 0.27050518, 0.63254946, 0.51443502],
       [0.7273545 , 0.32363951, 0.60005013, 0.90877338, 0.52504773],
       [0.09142845, 0.26159161, 0.67929638, 0.28716685, 0.43188455]])

In [13]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_arr_nums = np.random.randint(0, 10, size=(4, 6))
display(random_arr_nums)


array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [14]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_arr1 = np.random.randint(1, 10, size=(3, 7))
display(random_arr1)

# Find the unique numbers in the array you just created
np.unique(random_arr1)


array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

array([1, 2, 3, 4, 5, 7, 9])

In [15]:
# Find the 0'th index of the latest array you created
random_arr1[0]


array([9, 1, 3, 7, 4, 9, 3])

In [16]:
# Get the first 2 rows of latest array you created
display(random_arr1[0 : 2])


array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [145]:
# Get the first 2 values of the first 2 rows of the latest array
display(random_arr1[:2, :2])

array([[9, 1],
       [5, 3]])

In [74]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_arr2 = np.random.randint(0, 10, size=(3, 5))
ones_arr2 = np.ones(shape=(3, 5), dtype=int)

In [75]:
# Add the two arrays together
sum = random_arr2 + ones_arr2
display(sum)

array([[10,  7, 10,  9,  7],
       [ 9,  8,  2,  1,  7],
       [ 7,  8,  5,  3,  8]])

In [77]:
# Create another array of ones of shape (5, 3)
ones_arr3 = np.ones(shape=(5, 3), dtype=int)
ones_arr3

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [78]:
# Try add the array of ones and the other most recent array together
final_sum = ones_arr3 + sum
display(final_sum)

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [79]:
final_sum = ones_arr3.T + sum
display(final_sum)

array([[11,  8, 11, 10,  8],
       [10,  9,  3,  2,  8],
       [ 8,  9,  6,  4,  9]])

In [82]:
# Create another array of ones of shape (3, 5)
ones_arr4 = np.ones(shape=(3, 5), dtype=int)


In [83]:
# Subtract the new array of ones from the other most recent array
difference = final_sum - ones_arr4
display(difference)

array([[10,  7, 10,  9,  7],
       [ 9,  8,  2,  1,  7],
       [ 7,  8,  5,  3,  8]])

In [84]:
# Multiply the ones array with the latest array
product = difference * ones_arr4
display(product)


array([[10,  7, 10,  9,  7],
       [ 9,  8,  2,  1,  7],
       [ 7,  8,  5,  3,  8]])

In [85]:
# Take the latest array to the power of 2 using '**'
raise_to_two = product ** 2
display(raise_to_two)


array([[100,  49, 100,  81,  49],
       [ 81,  64,   4,   1,  49],
       [ 49,  64,  25,   9,  64]])

In [86]:
# Do the same thing with np.square()
arr_square = np.square(product)
display(arr_square)

array([[100,  49, 100,  81,  49],
       [ 81,  64,   4,   1,  49],
       [ 49,  64,  25,   9,  64]])

In [87]:
# Find the mean of the latest array using np.mean()
np.mean(arr_square)


52.6

In [90]:
# Find the maximum of the latest array using np.max()
np.max(arr_square)

100

In [91]:
# Find the minimum of the latest array using np.min()
np.min(arr_square)


1

In [92]:
# Find the standard deviation of the latest array
np.std(arr_square)

30.80649282213085

In [93]:
# Find the variance of the latest array
np.var(arr_square)


949.0399999999996

In [95]:
# Reshape the latest array to (3, 5, 1)
display(arr_square)
arr_square.reshape(3, 5, 1)

array([[100,  49, 100,  81,  49],
       [ 81,  64,   4,   1,  49],
       [ 49,  64,  25,   9,  64]])

array([[[100],
        [ 49],
        [100],
        [ 81],
        [ 49]],

       [[ 81],
        [ 64],
        [  4],
        [  1],
        [ 49]],

       [[ 49],
        [ 64],
        [ 25],
        [  9],
        [ 64]]])

In [96]:
# Transpose the latest array
arr_square.T

array([[100,  81,  49],
       [ 49,  64,  64],
       [100,   4,  25],
       [ 81,   1,   9],
       [ 49,  49,  64]])

What does the transpose do?

It reverses the shape from (3, 5, 1) to (1, 5, 3)

In [97]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random_x = np.random.randint(0, 10, size=(3, 3))
random_y = np.random.randint(0, 10, size=(3, 2))
display(random_x)
display(random_y)

array([[5, 2, 0],
       [2, 4, 2],
       [0, 4, 9]])

array([[6, 6],
       [8, 9],
       [9, 2]])

In [98]:
# Perform a dot product on the two newest arrays you created
np.dot(random_x, random_y)

array([[ 46,  48],
       [ 62,  52],
       [113,  54]])

In [121]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random_a = np.random.randint(0, 10, size=(4, 3))
random_b = np.random.randint(0, 10, size=(4, 3))
display(random_a)
display(random_b)

array([[8, 3, 8],
       [2, 6, 5],
       [7, 8, 4],
       [0, 2, 9]])

array([[7, 5, 7],
       [8, 3, 0],
       [0, 9, 3],
       [6, 1, 2]])

In [122]:
# Perform a dot product on the two newest arrays you created
np.dot(random_a, random_b)


ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [123]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(random_a, random_b.T)

array([[127,  73,  51,  67],
       [ 79,  34,  69,  28],
       [117,  80,  84,  58],
       [ 73,   6,  45,  20]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [124]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
display(random_a)
display(random_b)


array([[8, 3, 8],
       [2, 6, 5],
       [7, 8, 4],
       [0, 2, 9]])

array([[7, 5, 7],
       [8, 3, 0],
       [0, 9, 3],
       [6, 1, 2]])

In [125]:
# Compare the two arrays with '>'
display(random_a > random_b)

array([[ True, False,  True],
       [False,  True,  True],
       [ True, False,  True],
       [False,  True,  True]])

What happens when you compare the arrays with `>`?

In [126]:
# Compare the two arrays with '>='
display(random_a >= random_b)


array([[ True, False,  True],
       [False,  True,  True],
       [ True, False,  True],
       [False,  True,  True]])

In [127]:
# Find which elements of the first array are greater than 7
display(random_a > 7)


array([[ True, False,  True],
       [False, False, False],
       [False,  True, False],
       [False, False,  True]])

In [128]:
# Which parts of each array are equal? (try using '==')
display(random_a == random_b)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [129]:
# Sort one of the arrays you just created in ascending order
sorted_arr = np.sort(random_b)
display(random_b)
display(sorted_arr)



array([[7, 5, 7],
       [8, 3, 0],
       [0, 9, 3],
       [6, 1, 2]])

array([[5, 7, 7],
       [0, 3, 8],
       [0, 3, 9],
       [1, 2, 6]])

In [130]:
# Sort the indexes of one of the arrays you just created
sorted_arr.argsort()


array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [134]:
# Find the index with the maximum value in one of the arrays you've created
display(random_a)
display(random_a.argmax())

array([[8, 3, 8],
       [2, 6, 5],
       [7, 8, 4],
       [0, 2, 9]])

11

In [135]:
# Find the index with the minimum value in one of the arrays you've created
display(random_a)
display(random_a.argmin())


array([[8, 3, 8],
       [2, 6, 5],
       [7, 8, 4],
       [0, 2, 9]])

9

In [136]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
display(random_a)
display(random_a.argmax(axis=1))

array([[8, 3, 8],
       [2, 6, 5],
       [7, 8, 4],
       [0, 2, 9]])

array([0, 1, 1, 2], dtype=int64)

In [138]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
display(random_a)
display(random_a.argmin(axis=0))


array([[8, 3, 8],
       [2, 6, 5],
       [7, 8, 4],
       [0, 2, 9]])

array([3, 3, 2], dtype=int64)

In [147]:
# Create an array of normally distributed random numbers
np.random.seed(2)
random_nums = np.random.normal(size=(2, 5))
display(random_nums)


array([[-0.41675785, -0.05626683, -2.1361961 ,  1.64027081, -1.79343559],
       [-0.84174737,  0.50288142, -1.24528809, -1.05795222, -0.90900761]])

In [148]:
# Create an array with 10 evenly spaced numbers between 1 and 100
arr = np.arange(1, 101, 10)
display(arr)


array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.