In [1]:
import numpy as np

### Transpose

In [16]:
x = np.array([[10, 20, 30], 
              [40, 50, 60], 
              [70, 80, 90], 
              [100, 110, 120]])
display(x)
display(x.shape) # 4 columns with 3 elements
x_transpose = x.T
display(x_transpose)
display(x_transpose.shape) # 3 columns with 4 elements

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

(4, 3)

array([[ 10,  40,  70, 100],
       [ 20,  50,  80, 110],
       [ 30,  60,  90, 120]])

(3, 4)

In [23]:
y = np.array([[[10, 20, 30], 
               [40, 50, 60]],
              
              [[110, 120, 130],
               [140, 150, 160]],
              ])
display(y)
display(y.shape)
y_transpose = y.T
display(y_transpose)
display(y_transpose.shape)

array([[[ 10,  20,  30],
        [ 40,  50,  60]],

       [[110, 120, 130],
        [140, 150, 160]]])

(2, 2, 3)

array([[[ 10, 110],
        [ 40, 140]],

       [[ 20, 120],
        [ 50, 150]],

       [[ 30, 130],
        [ 60, 160]]])

(3, 2, 2)