In [4]:
import numpy as np

In [13]:
# Normal way of creating an arr
norm_arr = np.array([1, 2, 3])
display(norm_arr)
display(norm_arr.shape)
display(norm_arr.size)
display(norm_arr.ndim)

array([1, 2, 3])

(3,)

3

1

In [17]:
# Using np.arange()
arr_range = np.arange(1, 6)
display(arr_range)
display(arr_range.shape)
display(arr_range.size)
display(arr_range.ndim)

array([1, 2, 3, 4, 5])

(5,)

5

1

In [26]:
# Using np.zeros - either 1D or multi-dimension
z1 = np.zeros((3, 4), dtype=int)
z2 = np.zeros(3, dtype=int)
display(z1)
display(z2)
# if we don't specify the shape, it is automatically a 1D array

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

array([0, 0, 0])

In [42]:
# Using np.ones - either 1D or multi-dimension
o1 = np.ones((2, 5), dtype=int)
o2 = np.ones(5, dtype=int)
display(o1)
display(f'o1 Ndim: {o1.ndim}')
display(o2)
display(f'o2 Ndim: {o2.ndim}')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

'o1 Ndim: 2'

array([1, 1, 1, 1, 1])

'o2 Ndim: 1'

In [39]:
# Using np.random.randint
random_arr = np.random.randint(1, 50, size=(2, 4))
display(random_arr) 
display(random_arr.size)
display(random_arr.shape)
display(random_arr.ndim)

array([[10, 17, 41, 32],
       [43, 16, 40, 14]])

8

(2, 4)

2

In [43]:
x = 1_950
y = 2_220
print(x + y)

4170
