In [56]:
import numpy as np

In [57]:
random_arr = np.random.randint(1, 20, size=(2, 3, 4, 5))
display(random_arr)
# 2 parent array with 3 sub-array that contains 4 rows with 5 elements
'''
2 parent arrays (outermost dimension)
Each parent array contains 3 sub-arrays (next dimension)
Each sub-array has 4 rows
Each row contains 5 elements
- from ChatGPT
'''

array([[[[ 3, 10,  4, 14,  3],
         [ 5,  1, 11,  5,  4],
         [18, 10,  2,  6,  7],
         [11, 12, 12, 15,  3]],

        [[ 2,  7,  3, 18, 13],
         [ 1, 19,  7,  5,  5],
         [14,  9,  4,  1,  2],
         [10,  6,  4,  3, 10]],

        [[ 9,  4,  6,  9, 10],
         [ 5, 15,  8,  2, 18],
         [14, 11,  8, 14,  9],
         [ 9, 15,  3,  7,  6]]],


       [[[11,  8, 10,  9, 18],
         [ 3,  3, 12,  8, 19],
         [ 2, 16,  5, 10,  8],
         [15,  3,  2,  7,  3]],

        [[14,  7,  8,  6,  5],
         [18, 14,  4,  6,  4],
         [17, 14,  2,  2, 15],
         [ 3, 15,  2,  9, 19]],

        [[18, 10,  8,  4, 13],
         [ 7,  3, 16, 12, 12],
         [ 6,  6,  4,  3, 17],
         [ 8,  4, 11, 11, 12]]]])

'\n2 parent arrays (outermost dimension)\nEach parent array contains 3 sub-arrays (next dimension)\nEach sub-array has 4 rows\nEach row contains 5 elements\n- from ChatGPT\n'

In [58]:
display(random_arr)

array([[[[ 3, 10,  4, 14,  3],
         [ 5,  1, 11,  5,  4],
         [18, 10,  2,  6,  7],
         [11, 12, 12, 15,  3]],

        [[ 2,  7,  3, 18, 13],
         [ 1, 19,  7,  5,  5],
         [14,  9,  4,  1,  2],
         [10,  6,  4,  3, 10]],

        [[ 9,  4,  6,  9, 10],
         [ 5, 15,  8,  2, 18],
         [14, 11,  8, 14,  9],
         [ 9, 15,  3,  7,  6]]],


       [[[11,  8, 10,  9, 18],
         [ 3,  3, 12,  8, 19],
         [ 2, 16,  5, 10,  8],
         [15,  3,  2,  7,  3]],

        [[14,  7,  8,  6,  5],
         [18, 14,  4,  6,  4],
         [17, 14,  2,  2, 15],
         [ 3, 15,  2,  9, 19]],

        [[18, 10,  8,  4, 13],
         [ 7,  3, 16, 12, 12],
         [ 6,  6,  4,  3, 17],
         [ 8,  4, 11, 11, 12]]]])

In [59]:
display(random_arr[0])

array([[[ 3, 10,  4, 14,  3],
        [ 5,  1, 11,  5,  4],
        [18, 10,  2,  6,  7],
        [11, 12, 12, 15,  3]],

       [[ 2,  7,  3, 18, 13],
        [ 1, 19,  7,  5,  5],
        [14,  9,  4,  1,  2],
        [10,  6,  4,  3, 10]],

       [[ 9,  4,  6,  9, 10],
        [ 5, 15,  8,  2, 18],
        [14, 11,  8, 14,  9],
        [ 9, 15,  3,  7,  6]]])

In [60]:
display(random_arr[1])

array([[[11,  8, 10,  9, 18],
        [ 3,  3, 12,  8, 19],
        [ 2, 16,  5, 10,  8],
        [15,  3,  2,  7,  3]],

       [[14,  7,  8,  6,  5],
        [18, 14,  4,  6,  4],
        [17, 14,  2,  2, 15],
        [ 3, 15,  2,  9, 19]],

       [[18, 10,  8,  4, 13],
        [ 7,  3, 16, 12, 12],
        [ 6,  6,  4,  3, 17],
        [ 8,  4, 11, 11, 12]]])

In [61]:
display(random_arr[0][0])

array([[ 3, 10,  4, 14,  3],
       [ 5,  1, 11,  5,  4],
       [18, 10,  2,  6,  7],
       [11, 12, 12, 15,  3]])

In [62]:
display(random_arr[0][1])

array([[ 2,  7,  3, 18, 13],
       [ 1, 19,  7,  5,  5],
       [14,  9,  4,  1,  2],
       [10,  6,  4,  3, 10]])

In [63]:
display(random_arr[0][2])

array([[ 9,  4,  6,  9, 10],
       [ 5, 15,  8,  2, 18],
       [14, 11,  8, 14,  9],
       [ 9, 15,  3,  7,  6]])

### The number of indices determines which part of the array we want to access

In [65]:
display(random_arr[0][0][0][0])
# If we want to display a single element from the array, then it needs to match the length of shape which is 4

3

In [67]:
display(random_arr[0][0][0])

array([ 3, 10,  4, 14,  3])

In [68]:
display(random_arr[0][0])

array([[ 3, 10,  4, 14,  3],
       [ 5,  1, 11,  5,  4],
       [18, 10,  2,  6,  7],
       [11, 12, 12, 15,  3]])

In [69]:
display(random_arr[0])

array([[[ 3, 10,  4, 14,  3],
        [ 5,  1, 11,  5,  4],
        [18, 10,  2,  6,  7],
        [11, 12, 12, 15,  3]],

       [[ 2,  7,  3, 18, 13],
        [ 1, 19,  7,  5,  5],
        [14,  9,  4,  1,  2],
        [10,  6,  4,  3, 10]],

       [[ 9,  4,  6,  9, 10],
        [ 5, 15,  8,  2, 18],
        [14, 11,  8, 14,  9],
        [ 9, 15,  3,  7,  6]]])